### ISSUE TITLE
[FEATURE REQUEST] Add multiple slots for "OpenAI compatible" in "API provider" selection

### ISSUE THREAD

**Issue by PhunkyBob** [lee88688/aider-composer#31]
## Problem

I'm juggling with a lot of model providers (Groq, SambaNova, Cerebras, ...). But when I have to choose the API provider in Aider-composer parameters, there is only one place to set my endpoint / API key.
I have to change API key and URL every time I want to switch between model providers. 

## Feature request

In the "Provider" list, replace `OpenAI Compatible` with `OpenAI Compatible #1`, `OpenAI Compatible #2`, `OpenAI Compatible #3` and `OpenAI Compatible #4`. 
Thanks to this feature, I'll be able to store Groq's settings in slot number 1, Cerebras in slot number 2, etc..
If I want to change model, I juste have to select the one I want.

I already made the same request in another project, developed it and made the PR, but it has not been accepted yet. 
Since I prefer Aider to "the other project", this feature is a must have for me.

**Comment by lee88688** [comment]
I think this should be replaced multiple provider setting. users can add miltiple provider with name, and select from them.

**Comment by AlexJ-StL** [comment]
I am 100% with OP. I too use Groq, SombaNova, Cerebras, along with several others, both local (Ollama and LM Studio) and API (Gemini, Claude, Deepseek, etc.).

Implementing some kind of Model + API + URL list, such as the suggestion from another thread (I forget the number) to use the .aider.config.yml file would be fantastic.

Another suggestion would be to implement something like what 'Continue' does. They simply have a built in JSON that lists every model under the sun and you can simply go through and add your API keys. Personally I would like to see some kind of us of all the freaking Environmental Variables that I maintain instead of having to input these APIs all the time... #momodelsmoapiproblems

One last suggestion would be to simply provide LiteLLM support. You already have OpenRouter, which is a great service, but adding LiteLLM would drastically increase the users who could take advantage of your extension.

Cheers!
